# Destination folder
prefix = "$HOME/.config/polybar/scripts/ixwindow"

# Folder for cached icons
cache_dir = "$HOME/.config/polybar/scripts/ixwindow/polybar-icons"

# Folder for config icons
config_dir = "$HOME/.config/ixwindow/bspwm"
config_file = "config.toml"

# Size of the icon
size = 24

# Background color of your polybar
color = "#252737"

# Absolute coordinates of icon
x = 270
y = 6

# Amound of spaces in the title of the module, before title of the window
# This is to be adjusted together with coordinates of the icon to achieve the
# best result
gap = "         "
